### ISSUE TITLE
Windowsでpip install 不可

### ISSUE THREAD

**Issue by kazukitakamatsu** [studio-ousia/mojimoji#11]
現状、Windows環境で`pip install mojimoji` とすると0.0.8をインストールしようとしてunorderd_mapの問題にぶつかります。
最新版は`pip install mojimoji=0.0.9` では見つからず、`pip install mojimoji=0.0.9_2` でインストールできます。
PyPIへの登録の問題なのかもしれませんが、対処頂けると幸いです。

**Comment by ikuyamada** [comment]
イシューの報告をありがとうございます。バージョン番号を再度ふり直したものをPyPIにアップロードいたしました。`% pip install mojimoji` で0.0.9がインストール可能になっているかと思います。

**Comment by kazukitakamatsu** [comment]
対処、ありがとうございます。
`% pip install mojimoji` にて0.0.9がインストールできることを確認しました。
