### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [studio-ousia/mojimoji#18]
Problem
---------
On aarch64, ‘pip install mojimoji’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install mojimoji’ should download the wheels from pypi 

@ikuyamada Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by ikuyamada** [comment]
@odidev Hi, thanks for the pull request and sorry for keeping you waiting. I've just merged the pull request and released a new version (0.0.12) with the support of the aarch64 wheel! (cc: @curt-mitch)
