### ISSUE TITLE
OS X Support?

### ISSUE THREAD

**Issue by dmiyakawa** [studio-ousia/mojimoji#2]
Seems "<tr1/unorderd_map>" is not effective on OS X. Clang does not understand it and thus compile fails.

Simple solution for my Mac would be removing "tr1" happening in mojimoji.cpp, while it makes debian wheezy unhappy instead (as the os uses gcc 4.7 which requests "-std=c++11" option)

https://github.com/dmiyakawa/mojimoji/commit/5d4299ddcdb91f5e015390b3b4a14b69449118fe

**Comment by ikuyamada** [comment]
Thank you for reporting the issue.
I hope the problem is now fixed in the latest PyPI package.
