### ISSUE TITLE
バックスラッシュが変換されない

### ISSUE THREAD

**Issue by nkmk** [studio-ousia/mojimoji#21]
バックスラッシュ（`\`: U+005C, `＼`: U+FF3C）が変換されません。

```py
>>> print(mojimoji.han_to_zen('\\'))
\
>>> print(mojimoji.zen_to_han('＼'))
＼
```

`mojimoji.pyx`の`ASCII_ZENKAKU_CHARS`と`ASCII_HANKAKU_CHARS`にバックスラッシュが設定されていないようです。
可能でしたら追加していただけると幸いです。

**Comment by ikuyamada** [comment]
イシューを報告いただきありがとうございます。
バックスラッシュが正しく変換されるように変更いたしました。
