### ISSUE TITLE
Add a link to a Go port to Readme

### ISSUE THREAD

**Issue by rusq** [studio-ousia/mojimoji#22]
Hey hey!

I discovered this library from this article [Slackdump_v2.2.0 Katakana charactors directory problem](https://phst.hateblo.jp/entry/2022/08/31/210000). And as I'm planning to implement  the same type of conversion in [slackdump](https://github.com/rusq/slackdump), I ported the logic is this library to Go: https://github.com/rusq/gomojimoji

I was wondering if you'd be interested to link it in your Readme file to help other people to find it?

Thank you!

BTW: Great work on making the conversion superfast with Cython!

Kind regards,
Rustam

**Comment by ikuyamada** [comment]
Hi @rusq ,
Thank you for letting me know your awesome work😍
I've added a link to your repository in the README!
