### ISSUE TITLE
インストール時にエラーが・・・

### ISSUE THREAD

**Issue by suteppi** [studio-ousia/mojimoji#4]
Python Vason 3.5.2にてインストールにエラーが発生してしまうのですが解決方法はありますか？
↓コマンドログ
C:\WINDOWS\system32>pip install mojimoji
Collecting mojimoji
  Using cached mojimoji-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sutep\AppData\Local\Temp\pip-build-t1q268nc\mojimoji\setup.py", line 14, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 563: illegal multibyte sequence

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\sutep\AppData\Local\Temp\pip-build-t1q268nc\mojimoji\

**Comment by twfronteo** [comment]
Hi, how is this issue going?
When I tried to install mojimoji under python 3.5, I am also trapped in this problem and here is the output.

`Downloading mojimoji-0.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hddwqkij/mojimoji/setup.py", line 14, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 554: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hddwqkij/mojimoji/
`

**Comment by ikuyamada** [comment]
Thank you for reporting the issue.
Currently, this library does not support Python 3.
Further, this specific error is caused because *setup.py* reads the README.rst file internally which contains non-unicode characters.
Pull requests are always welcomed! 😄
