### ISSUE TITLE
常用外のカナと濁点の組み合わせでのバグ(？)

### ISSUE THREAD

**Issue by kirk3110** [studio-ousia/mojimoji#5]
意図していない挙動のように思われるので報告させていただきます。

### 概要
常用外のカナと濁点の組み合わせ（"ｱﾞ", "ｶﾟ"など）にhan_to_zenすると、その組み合わせが出現した時点で中断された文字列がreturnされる。

### 例
```python
>>> import mojimoji
>>> print mojimoji.han_to_zen(u'ｶﾞｷﾞｸﾞｹﾞｺﾞ')
ガギグゲゴ    # 常用の組み合わせ→OK
>>> print mojimoji.han_to_zen(u'アイウエオｱﾞｲﾞｳﾞｴﾞｵﾞあいうえお')
アイウエオ    # 常用外の組み合わせ→NG
```
### 環境
mojimoji: 0.0.5
Windows7 / Python2.7.10

kana_ten_hz_tableなどのテーブルを参照しにいった際、該当するものがないと終端文字に置き換わってしまっているような挙動です。

**Comment by ikuyamada** [comment]
レポートいただきありがとうございました。
上記のコミットで修正しました。

**Comment by ikuyamada** [comment]
修正を含んだバージョンv0.0.6をPyPIにリリースしました。
