### ISSUE TITLE
building on windows

### ISSUE THREAD

**Issue by Dobatymo** [studio-ousia/mojimoji#8]
It can be built on windows using VS if

`cdef extern from "<tr1/unordered_map>" namespace "std::tr1":`
is replaced by
`cdef extern from "<unordered_map>" namespace "std":`

also building is easier if
```
from Cython.Build import cythonize
ext_modules = cythonize('mojimoji.pyx')
```
is used.

**Comment by ikuyamada** [comment]
Thank you for your comment.
- *unordered_map* is now included in the latest Cython release, so I modified the code to use it in the latest commit.
- I avoid using *cythonize* in setup.py because using it in setup.py requires users to install Cython.
