### ISSUE TITLE
インストール時のエラー（Microsoft Visual C++ 14.0 is required.)

### ISSUE THREAD

**Issue by misa1990** [studio-ousia/mojimoji#9]
Windows 7、Python3.6.5からpipでインストールしようとしたところ、下記のエラーが発生しました。

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

記載のURLに遷移すると、期限切れらしくビルドツールのダウンロードはできませんでした。
どうすればよろしいでしょうか。

よろしくお願いいたします。

**Comment by ikuyamada** [comment]
手元にWindows環境が無いため分かりませんが、おそらくこのライブラリ特有の問題ではなく、一般的なCで実装されたPythonのライブラリがインストールできない状態なのではないかと思います。オンラインの説明等を参照していただいて、解決をお願いできればと思います。
